#!/bin/bash
npm run build
cp ./dist/bundle.js ../backend/src/main/resources/static/bundle.js
cp -r ./src/components/html ../backend/src/main/resources/static/html
cp -r ./images ../backend/src/main/resources/static/images
cp -r ./assets ../backend/src/main/resources/static/assets